name: flutter_sound_web
version: 9.4.14
description: Flutter plugin that relates to sound like audio and recorder.
#author: canardoux<larpoux@gmail.com>
homepage: https://flutter-sound.canardoux.xyz/
environment:
    sdk: ^3.3.0
    flutter: ">=2.0.0"

# 0.1.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterSoundPlugin
        fileName: flutter_sound_web.dart
        
  assets:
  - howler/howler.js
  - src/flutter_sound.js
  - src/flutter_sound_player.js
  - src/flutter_sound_recorder.js
  


dependencies:
  flutter_sound_platform_interface: 9.4.14
#    path: ../flutter_sound_platform_interface # Flutter Sound Dir
  flutter:
    sdk: flutter
  logger: ^2.0.2
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
 
